// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tostadasoft.GitRepositoryWindowForever
{
    internal sealed partial class Vsix
    {
        public const string Id = "GitRepoWindowForever.3414a3ef-ce9e-477b-8abb-7adf619775b6";
        public const string Name = "GitRepoWindowForever";
        public const string Description = @"An extension for Visual Studio 2022 to ensure that the Git Repository Window is always shown on startup, on solution load, and upon debugging your solution.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Tostadasoft";
        public const string Tags = "";
    }
}
