// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tostadasoft.GitRepositoryWindowForever
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GitRepositoryWindowForeverString = "3414a3ef-ce9e-477b-8abb-7adf619775b6";
        public static Guid GitRepositoryWindowForever = new Guid(GitRepositoryWindowForeverString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {

    }
}